alias: Boiler Monitor - Notify
description: Skickar notis när pannans larmlampa upptäcks.
mode: single
trigger:
  - platform: state
    entity_id: binary_sensor.boiler_monitor_alarm
    to: "on"
    for:
      milliseconds: 300
action:
  - service: notify.mobile_app_DIN_TELEFON
    data:
      title: "Pannlarm"
      message: "Värmepannans röda larmlampa är aktiv."
  - service: persistent_notification.create
    data:
      title: "Pannlarm"
      message: "Boiler Monitor har upptäckt att pannans röda larmlampa är aktiv."
