binary_sensor:
  - platform: gpio
    id: mute_button
    name: "${friendly_name} Mute Button"
    pin:
      number: GPIO22
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on: 30ms
      - delayed_off: 30ms
    on_press:
      then:
        - lambda: |-
            id(alarm_muted) = true;
        - output.turn_off: buzzer_output

button:
  - platform: template
    name: "${friendly_name} Test Buzzer"
    on_press:
      then:
        - output.turn_on: buzzer_output
        - delay: 750ms
        - output.turn_off: buzzer_output
