binary_sensor:
  - platform: gpio
    id: mute_button
    name: "${friendly_name} Mute Button"
    pin:
      number: GPIO22
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on: 30ms
      - delayed_off: 30ms
    on_press:
      then:
        - lambda: |-
            id(alarm_muted) = true;
        - output.turn_off: buzzer_output

button:
  - platform: template
    name: "${friendly_name} Acknowledge Alarm"
    icon: mdi:bell-cancel
    on_press:
      then:
        - lambda: |-
            id(alarm_muted) = true;
        - output.turn_off: buzzer_output

  - platform: template
    name: "${friendly_name} Reset Latched Alarm"
    icon: mdi:restore-alert
    on_press:
      then:
        - lambda: |-
            id(alarm_latched) = false;
            id(alarm_muted) = false;
        - output.turn_off: buzzer_output

  - platform: template
    name: "${friendly_name} Test Buzzer"
    icon: mdi:volume-source
    on_press:
      then:
        - if:
            condition:
              switch.is_on: buzzer_enabled
            then:
              - output.turn_on: buzzer_output
              - delay: 1s
              - output.turn_off: buzzer_output

  - platform: template
    name: "${friendly_name} Run Hardware Test"
    icon: mdi:test-tube
    on_press:
      then:
        - output.turn_off: green_led_output
        - output.turn_on: red_led_output
        - if:
            condition:
              switch.is_on: buzzer_enabled
            then:
              - output.turn_on: buzzer_output
        - delay: 1s
        - output.turn_off: buzzer_output
        - delay: 2s
        - output.turn_off: red_led_output
        - output.turn_on: green_led_output
