text_sensor:
  - platform: template
    name: "${friendly_name} Firmware Version"
    icon: mdi:tag
    entity_category: diagnostic
    lambda: |-
      return std::string("${firmware_version}");

  - platform: template
    name: "${friendly_name} Last Alarm"
    id: last_alarm_text
    icon: mdi:clock-alert
    update_interval: never

  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      entity_category: diagnostic
    ssid:
      name: "${friendly_name} Connected SSID"
      entity_category: diagnostic
    mac_address:
      name: "${friendly_name} MAC Address"
      entity_category: diagnostic

sensor:
  - platform: wifi_signal
    id: wifi_rssi
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s
    entity_category: diagnostic

  - platform: copy
    source_id: wifi_rssi
    name: "${friendly_name} WiFi Signal Percent"
    unit_of_measurement: "%"
    entity_category: diagnostic
    filters:
      - lambda: |-
          if (x <= -100.0) return 0.0;
          if (x >= -50.0) return 100.0;
          return 2.0 * (x + 100.0);

  - platform: uptime
    name: "${friendly_name} Uptime"
    update_interval: 60s
    entity_category: diagnostic

button:
  - platform: restart
    name: "${friendly_name} Restart"
    entity_category: diagnostic
