text_sensor:
  - platform: template
    name: "${friendly_name} Firmware Version"
    lambda: |-
      return std::string("${firmware_version}");

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "${friendly_name} Uptime"
