sensor:
  - platform: adc
    pin: GPIO34
    id: boiler_led_level
    name: "${friendly_name} LED Level"
    attenuation: 11db
    update_interval: 100ms
    accuracy_decimals: 3
    filters:
      - exponential_moving_average:
          alpha: 0.25
          send_every: 1

number:
  - platform: template
    id: boiler_led_threshold
    name: "${friendly_name} LED Threshold"
    optimistic: true
    restore_value: true
    initial_value: 1.20
    min_value: 0.05
    max_value: 3.10
    step: 0.05
    unit_of_measurement: "V"
    mode: slider
