substitutions:
  device_name: boiler-monitor
  friendly_name: Boiler Monitor
  firmware_version: "0.8.0"

packages:
  base: !include packages/base.yaml
  diagnostics: !include packages/diagnostics.yaml
  outputs: !include packages/outputs.yaml
  sensor: !include packages/sensor.yaml
  temperature: !include packages/temperature_ds18b20.yaml
  alarm_logic: !include packages/alarm_logic.yaml
  buttons: !include packages/buttons.yaml
